name:                randamLaunch
version:             0.1.0.0
github:              "residenti/randamLaunch"
license:             BSD3
author:              "residenti"
maintainer:          "n.queue.r@gmail.com"
copyright:           "Copyright (c) 2022 residenti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/residenti/randamLaunch#readme>

dependencies:
- base >= 4.7 && < 5
- random
- scalpel
- text

library:
  source-dirs: src

executables:
  randamLaunch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - randamLaunch
    # https://github.com/commercialhaskell/stack/issues/5439
    when:
    - condition: false
      other-modules: Paths_randamLaunch

tests:
  randamLaunch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - randamLaunch
