name:                randam-lunch-printer
version:             1.1.1
github:              "residenti/randam-lunch-printer"
license:             MIT
author:              "residenti"
maintainer:          "n.queue.r@gmail.com"
copyright:           "Copyright (c) 2022 residenti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/residenti/randam-lunch-printer#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- directory
- http-conduit
- random
- unix

default-extensions:
  OverloadedStrings
  , DeriveGeneric

library:
  source-dirs: src

executables:
  lunch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - randam-lunch-printer
    # https://github.com/commercialhaskell/stack/issues/5439
    when:
    - condition: false
      other-modules: Paths_randam-lunch-printer

tests:
  randam-lunch-printer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - randam-lunch-printer
